filer/urls.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import

from django.conf.urls import url

from . import settings as filer_settings
from . import views

urlpatterns = [
    url(
        filer_settings.FILER_CANONICAL_URL + r'(?P<uploaded_at>[0-9]+)/(?P<file_id>[0-9]+)/$',  # flake8: noqa
        views.canonical,
        name='canonical'
    ),
]

gou/urls.py
# coding: utf-8
from django.conf.urls import url
from gou.views import Home, ItemList, OrderList, ProfileDetail

urlpatterns = [
    url(r'^$', Home.as_view(), name='home'),
    url(r'^items/$', ItemList.as_view(), name='items'),
    url(r'^cart/$', OrderList.as_view(), name='cart'),
    url(r'^me/$', ProfileDetail.as_view(), name='me'),
]

gougo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^filer/', include('filer.server.urls')),
    url(r'^', include('gou.urls', namespace='gou')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gou/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from filer.fields.image import FilerImageField
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Item(models.Model):
    name = models.CharField(_('name'), max_length=255)
    image = FilerImageField(null=True, blank=True, related_name='item_images')
    price = models.IntegerField(_('price'))
    description = models.TextField(_('description'))
    created = models.DateTimeField(_('created time'), auto_now_add=True)
    updated = models.DateTimeField(_('updated time'), auto_now=True)

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        db_table = 'item'
        ordering = ['-created']

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Order(models.Model):
    item = models.ForeignKey(
        Item,
        related_name='orders',
        verbose_name=_('item')
    )
    user = models.ForeignKey(
        User,
        related_name='orders',
        verbose_name=_('item')
    )
    money = models.IntegerField(_('money'))
    created = models.DateTimeField(_('created time'), auto_now_add=True)

    class Meta:
        verbose_name = _('order')
        verbose_name_plural = _('orders')
        db_table = 'order'
        ordering = ['-created']

    def __str__(self):
        return '%s: %s' % (self.user.username, self.item.name)


@python_2_unicode_compatible
class ItemInt(models.Model):
    item = models.ForeignKey(
        Item,
        related_name='itemInts',
        verbose_name=_('item')
    )
    user = models.ForeignKey(
        User,
        related_name='itemInts',
        verbose_name=_('user')
    )

    class Meta:
        verbose_name = _('itemInts')
        verbose_name_plural = _('itemInts')
        db_table = 'item_int'

    def __str__(self):
        return '%s: %s' % (self.user.username, self.item.name)


@python_2_unicode_compatible
class Cart(models.Model):
    user = models.ForeignKey(
        User,
        related_name='carts',
        verbose_name=_('cart')
    )
    item = models.ForeignKey(
        Item,
        related_name='carts',
        verbose_name=_('item')
    )
    created = models.DateTimeField(_('created time'), auto_now_add=True)

    class Meta:
        unique_together = ('user', 'item')
        verbose_name = _('cart')
        verbose_name_plural = _('carts')
        db_table = 'cart'
        ordering = ['-created']

    def __str__(self):
        return '%s: %s' % (self.user.username, self.item.name)


@python_2_unicode_compatible
class Profile(models.Model):

    GENDER = (
        (1, _('man')),
        (0, _('woman')),
    )
    user = models.OneToOneField(
        User,
        related_name='profile',
        verbose_name=_('profile')
    )
    nickname = models.CharField(_('nickname'), max_length=100)
    gender = models.IntegerField(_('gender'), choices=GENDER)
    phone = models.CharField(_('phone'), max_length=20)
    qq = models.CharField(_('qq'), max_length=20)
    weixin = models.CharField(_('weixin'), max_length=50)
    address = models.CharField(_('address'), max_length=200)

    def __str__(self):
        return self.nickname

gou/views/cart.py
# coding: utf-8

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from gou.models import Order


class OrderList(ListView):
    template_name = 'order.html'
    model = Order
    context_object_name = 'orders'

    def get_context_data(self, **kwargs):
        context = super(OrderList, self).get_context_data(**kwargs)
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(OrderList, self).dispatch(*args, **kwargs)

gou/views/home.py
# coding: utf-8

from django.views.generic import ListView
from gou.models import Item


class Home(ListView):
    template_name = 'home.html'
    model = Item
    context_object_name = 'items'

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        context['populated'] = Item.objects.all()[:4]
        context['shared'] = Item.objects.all()[:4]
        return context

gou/views/item_int.py
# coding: utf-8

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from gou.models import ItemInt


class ItemIntList(ListView):
    template_name = 'order.html'
    model = ItemInt
    context_object_name = 'ints'

    def get_context_data(self, **kwargs):
        context = super(ItemIntList, self).get_context_data(**kwargs)
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ItemIntList, self).dispatch(*args, **kwargs)

gou/views/items.py
# coding: utf-8

from django.views.generic import ListView
from gou.models import Item


class ItemList(ListView):
    template_name = 'items.html'
    model = Item
    context_object_name = 'items'

    def get_context_data(self, **kwargs):
        context = super(ItemList, self).get_context_data(**kwargs)
        context['finishing'] = Item.objects.all()[:4]
        return context

gou/views/profile.py
# coding: utf-8

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView
from gou.models import Profile


class ProfileDetail(UpdateView):
    template_name = 'profile.html'
    model = Profile
    context_object_name = 'profile'
    fields = ['nickname', 'gender', 'phone', 'qq', 'weixin', 'address']

    def get_object(self, queryset=None):
        try:
            return self.request.user.profile
        except:
            return None

    def get_success_url(self):
        return '/me/'

    def get_context_data(self, **kwargs):
        context = super(ProfileDetail, self).get_context_data(**kwargs)
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProfileDetail, self).dispatch(*args, **kwargs)

gou/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh_CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}一元订制-首页{% endblock %}</title>
    <meta name="description" content="一元订制放心旅游">
    <meta name="keywords" content="一元订制,旅游">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="{% static 'js/libs/bootstrap/ie8-responsive-file-warning.js' %}"></script><![endif]-->
    <script src="{% static 'js/libs/bootstrap/ie-emulation-modes-warning.js' %}"></script>
  </head>
  <body>
    {% block content %}
    {% endblock %}
    <script src="{% static 'js/libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/libs/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/libs/TouchSlide/TouchSlide.min.js' %}"></script>
    <script src="{% static 'js/comm.js' %}"></script>
    <script>
      $(function(){
          TouchSlide({ 
              slideCell:"#banner",
              titCell:".hd ul",
              mainCell:".bd ul", 
              effect:"leftLoop", 
              autoPage:true,
              autoPlay:true,      
              delayTime:500,
              interTime:3000
          });
      });
    </script>
  </body>
</html>

gou/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <nav class="navbar navbar-inverse navbar-fixed-bottom" id="menu">
    <ul class="nav navbar-nav">
      <li class="active"><a class="nav-home" href="/"><span></span>首页</a></li>
      <li><a class="nav-product" href="/items/"><span></span>全部旅途</a></li>
      <li><a class="nav-cart" href="/cart/"><span></span>购物车</a></li>
      <li><a class="nav-member" href="/me/"><span></span>个人中心</a></li>
    </ul>
  </nav>
  <header class="header">
    <img src="{% static 'img/logo.png' %}">
  </header>
  <div class="banner" id="banner">
    <div class="bd">
      <ul>
        <li>
          <a class="pic" href="#"><img src="{% static 'img/banner.jpg' %}"></a>
        </li>
        <li>
          <a class="pic" href="#"><img src="{% static 'img/banner.jpg' %}"></a>
        </li>
        <li>
          <a class="pic" href="#"><img src="{% static 'img/banner.jpg' %}"></a>
        </li>
      </ul>
    </div>
    <div class="hd">
      <ul>
      </ul>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="popularArea">
    <h1><span></span>最聚人气</h1>
    <ul>
      {% for item in populated %}
        <li>
          <div class="liCon">
            <p>{{ item.name }}</p>
            <h2>5700/6200</h2>
            <span><em style="width:90%"></em></span></div>
          <div class="liImg">
            <img src="{% static 'img/index-02.jpg' %}" width="135" height="102">
          </div>
          <div class="clearfix"></div>
        </li>
      {% endfor %}
      <div class="clearfix"></div>
    </ul>
  </div>
  <div class="popularAbroad">
    <dl>
      <dt><img src="{% static 'img/index-05.jpg' %}" width="350" height="221"></dt>
      <dd>
        <span>一元澳洲行 <em>全程代订</em></span>
        <img src="{% static 'img/index-06.jpg' %}" width="195" height="105">
        <div class="clearfix"></div>
      </dd>
      <dd>
        <span>一元澳洲行 <em>全程代订</em></span>
        <img src="{% static 'img/index-07.jpg' %}" width="195" height="106">
        <div class="clearfix"></div>
      </dd>
      <dd>
        <span>一元澳洲行 <em>全程代订</em></span>
        <img src="{% static 'img/index-08.jpg' %}" width="195" height="106">
        <div class="clearfix"></div>
      </dd>
      <dd>
        <span>一元澳洲行 <em>全程代订</em> </span>
        <img src="{% static 'img/index-09.jpg' %}" width="195" height="106">
        <div class="clearfix"></div>
      </dd>
      <div class="clearfix"></div>
    </dl>
  </div>
  <div class="hothare">
    <h1>订友分享</h1>
    <dl>
      <dt> <img src="{% static 'img/index-010.jpg' %}" width="355" height="361"> </dt>
      <dd> <img src="{% static 'img/index-011.jpg' %}" width="350" height="178"> </dd>
      <dd> <img src="{% static 'img/index-012.jpg' %}" width="350" height="178"> </dd>
      <div class="clearfix"></div>
    </dl>
  </div>
{% endblock %}

gou/templates/items.html
{% extends "base.html" %}
{% load staticfiles thumbnail current_count %}

{% block title %}一元订制-全部旅途{% endblock %}
{% block content %}
<nav class="navbar navbar-inverse navbar-fixed-bottom" id="menu">
  <ul class="nav navbar-nav">
    <li><a class="nav-home" href="/"><span></span>首页</a></li>
    <li class="active"><a class="nav-product" href="/items/"><span></span>全部旅途</a></li>
    <li><a class="nav-cart" href="/cart/"><span></span>购物车</a></li>
    <li><a class="nav-member" href="/me/"><span></span>个人中心</a></li>
  </ul>
</nav>
<nav class="navbar navbar-inverse" id="menuTop">全部旅途</nav>
<div class="product">
  <ul class="nav nav-tabs productNav">
    <li class="active"><a href="#producta" data-toggle="tab">你想去哪</a></li>
    <li><a href="#productb" data-toggle="tab">即将揭晓</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="producta">
      <ul>
        {% for item in items %}
          <li>
            <div class="poductImg">
              <img src="{% thumbnail item.image 200x200 crop %}">
            </div>
            <div class="productCon">
              <p>{{ item.description }}</p>
              <h1>价值：{{ item.price }}</h1>
              <h2>{{ item.id|count }}/{{ item.price }}</h2>
              <span class="productSpan">
                <em style="width:{{ item.id|count }} * 100/{{ item.price }}%"></em>
                </span><a class="productA" href="#">订制</a>
              </div>
            <div class="clearfix"></div>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="tab-pane" id="productb">
      <ul>
        {% for item in finishing %}
          <li>
            <div class="poductImg">
              <img src="{% thumbnail item.image 200x200 crop %}">
            </div>
            <div class="productCon">
              <p>{{ item.description }}</p>
              <h1>价值：{{ item.price }}</h1>
              <h2>{{ item.id|count }}/{{ item.price }}</h2>
              <span class="productSpan">
                <em style="width:{{ item.id|count }} * 100/{{ item.price }}%"></em>
              </span>
              <a class="productA" href="#">订制</a> </div>
            <div class="clearfix"></div>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

gou/templates/order.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <nav class="navbar navbar-inverse navbar-fixed-bottom" id="menu">
    <ul class="nav navbar-nav">
      <li><a class="nav-home" href="/"><span></span>首页</a></li>
      <li><a class="nav-product" href="/items/"><span></span>全部旅途</a></li>
      <li class="active"><a class="nav-cart" href="/cart/"><span></span>购物车</a></li>
      <li><a class="nav-member" href="/me/"><span></span>个人中心</a></li>
    </ul>
  </nav>
<!--导航 end-->
<nav class="navbar navbar-inverse" id="menuTop">购物车</nav>
<!--顶部栏目 end-->
<div class="cartcenter">
  <div class="tab-pane" id="producta">
    <ul>
      {% for order in orders%}
        <li>
          <div class="poductImg"><img src="img/index-01.jpg"></div>
          <div class="productCon">
            <p>(第1200订)云南双人5日双飞 游丽江，玉龙雪山.. </p>
            <h1>剩余3025人次</h1>
            <span class="cartCenter"><em>参与人次</em>
            <input type="text" value="111">
            <i>1111元</i><a href="#">订制</a></span>
            <div class="clearfix"></div>
          </div>
          <div class="clearfix"></div>
        </li>
      {% endfor %}
    </ul>
  </div>
</div>
<nav class="navbar navbar-inverse navbar-fixed-bottom" id="cartCount">
  <span>共<em>0</em>种订制，合计<em>0</em>元</span>
  <a href="#">结算</a>
</nav>
{% endblock %}

gou/templates/profile.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<nav class="navbar navbar-inverse navbar-fixed-bottom" id="menu">
    <ul class="nav navbar-nav">
      <li><a class="nav-home" href="/"><span></span>首页</a></li>
      <li><a class="nav-product" href="/items/"><span></span>全部旅途</a></li>
      <li><a class="nav-cart" href="/cart/"><span></span>购物车</a></li>
      <li class="active"><a class="nav-member" href="/me/"><span></span>个人中心</a></li>
    </ul>
  </nav>
<!--导航 end-->
<nav class="navbar navbar-inverse" id="menuTop">个人中心</nav>
<!--顶部栏目 end-->
<form id="loginform" method="post" action="">{% csrf_token %}
<div class="orderMan">
  <div class="orderInfora">
    <p><img src="{% static 'img/orderTou.jpg' %}"></p>
    <span>
      {{ form.nickname.value }}<em>({{ form.phone.value }})</em>
      <i>个性签名：想去哪玩去哪玩</i>
    </span>
    <div class="clearfix"></div>
  </div>
  <div class="orderInforb">
    <ul>
      <li><span>昵称：</span>
        <input type="text" class="form-control txta" value="{{ form.nickname.value }}" name="nickname">
        <div class="clearfix"></div>
      </li>
      <li>
        <span>性别：</span>
        <select class="form-control sele" id="id_gender" name="gender">
          <option value="">---------</option>
          <option value="1" {% if form.gender.value == 1 %}selected="selected"{% endif %}>男</option>
          <option value="0" {% if form.gender.value == 0 %}selected="selected"{% endif %}>女</option>
        </select>
        <div class="clearfix"></div>
      </li>

      <li><span>电话：<em>（备用联系不做公开）</em></span>
        <input type="text" class="form-control txta" value="{{ form.phone.value }}"  name="phone">
        <div class="clearfix"></div>
      </li>
      <li><span>QQ：<em>（备用联系不做公开）</em></span>
        <input type="text" class="form-control txta" value="{{ form.qq.value }}" name="qq">
        <div class="clearfix"></div>
      </li>
      <li><span>QQ：<em>（备用联系不做公开）</em></span>
        <input type="text" class="form-control txta" value="{{ form.weixin.value }}" name="weixin">
        <div class="clearfix"></div>
      </li>
      <li><span>地址：<em>（备用联系不做公开）</em></span>
        <input type="text" class="form-control txtb" value="{{ form.address.value }}" name="address">
        <div class="clearfix"></div>
      </li>
    </ul>
    <div class="orderBtn">
      <button type="submit" class="btn btn-default">保存</button>
    </div>
  </div>
</div>
</form>
{% endblock %}